package com.ravijain.sankalp.support;

/**
 * Created by ravijain on 7/5/2016.
 */
public interface SpConstants {


     int ACTIVITY_REQUEST_CODE = 100;
     String INTENT_KEY_SANKALP_TYPE = "SANKALP_TYPE";
     String INTENT_KEY_SANKALP_LIST_FILTER = "SANKALP_LIST_FILTER";
     String INTENT_KEY_SANKALP_LIST_FILTER_DATE_VALUE = "SANKALP_LIST_FILTER_DATE_VALUE";
     String INTENT_KEY_SANKALP_PERIOD = "INTENT_KEY_SANKALP_PERIOD";
     String INTENT_KEY_SIMPLE_DIALOG_ITEM_TYPE = "INTENT_KEY_SIMPLE_DIALOG_ITEM_TYPE";
     String INTENT_KEY_SIMPLE_DIALOG_ITEM_TYPE_ID = "INTENT_KEY_SIMPLE_DIALOG_ITEM_TYPE_ID";
     String INTENT_KEY_NUMBER_PICKER_TITLE = "INTENT_KEY_NUMBER_PICKER_TITLE";
     String INTENT_KEY_NUMBER_PICKER_TYPE = "INTENT_KEY_NUMBER_PICKER_TYPE";
    // String INTENT_KEY_SANKALP_LIST_FILTER_SANKALP_TYPE = "SANKALP_TYPE_FILTER";

     int INTENT_VALUE_SANKALP_LIST_FILTER_CURRENT = 0;
     int INTENT_VALUE_SANKALP_LIST_FILTER_UPCOMING = 2;
     int INTENT_VALUE_SANKALP_LIST_FILTER_ALL = 3;
     int INTENT_VALUE_SANKALP_LIST_FILTER_LIFETIME = 1;
     int INTENT_VALUE_SANKALP_LIST_FILTER_TODAY = 4;
     int INTENT_VALUE_SANKALP_LIST_FILTER_TOMORROW = 5;
     int INTENT_VALUE_SANKALP_LIST_FILTER_MONTH = 6;
     int INTENT_VALUE_SANKALP_LIST_FILTER_YEAR = 7;
     int INTENT_VALUE_SANKALP_LIST_FILTER_DAY = 8;
     int INTENT_VALUE_SANKALP_LIST_FILTER_RANGE = 9;

     String INTENT_KEY_SANKALP_ID = "SANKALP_ID";
     String IS_USER_ALREADY_CREATED = "IS_USER_ALREADY_CREATED";

     int SANKALP_TYPE_TYAG = 0;
     int SANKALP_TYPE_NIYAM = 1;
     int SANKALP_TYPE_BOTH = 2;
     int SANKALP_IS_LIFTIME_FALSE = 0;
     int SANKALP_IS_LIFTIME_TRUE = 1;

     String FRAGMENT_TAG_DESCRIPTION = "description";
     String FRAGMENT_TAG_EXTAR = "exTar";
     String FRAGMENT_TAG_CURRENT_COUNT = "currentCount";
     String FRAGMENT_TAG_ITEM = "item";
     String FRAGMENT_TAG_CATEGORY = "category";
     String FRAGMENT_TAG_FILTER = "filter";
     String FRAGMENT_TAG_INTERVAL = "interval";
     String FRAGMENT_TAG_SORT = "sort";
    String FRAGMENT_TAG_DAILY_SANKALP = "dailySankalp";

     String INTENT_SORTID = "INTENT_SORTID";
     int SORT_ORDER_ASCENDING = 1;
     int SORT_ORDER_DESCENDING = -1;
    String FRAGMENT_TAG_USER_PROFILE = "user_profile";
    String FRAGMENT_TAG_HISTORY = "hstory";
}
